/**
 * Source Attribution for TheervuAI
 *
 * Provides a clear taxonomy distinguishing verified official information
 * from AI-generated guidance. This is critical for user trust and
 * zero-fabrication compliance.
 *
 * Attribution levels:
 * - VERIFIED_OFFICIAL: Sourced from .gov.in / .nic.in with recent verification date
 * - VERIFIED_INSTITUTIONAL: Sourced from statutory body (UIDAI, EPFO, etc.)
 * - SYSTEM_GUIDANCE: AI-generated guidance, not tied to a specific official source
 * - USER_PROVIDED: Information the user themselves entered
 * - REQUIRES_CONFIRMATION: Information that may be outdated or location-dependent
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type SourceTier =
  | 'VERIFIED_OFFICIAL'
  | 'VERIFIED_INSTITUTIONAL'
  | 'SYSTEM_GUIDANCE'
  | 'USER_PROVIDED'
  | 'REQUIRES_CONFIRMATION'

export type FreshnessStatus = 'fresh' | 'recently_verified' | 'review_due' | 'unknown'

export interface SourceRecord {
  title: string
  url: string
  department: string
  authority: string
  state: 'All India' | string
  tier: SourceTier
  lastVerifiedAt: string | null
  reviewDueAt?: string | null
  freshnessStatus: FreshnessStatus
  notes?: string
}

export interface AttributionBadge {
  label: string
  description: string
  tier: SourceTier
  color: 'green' | 'blue' | 'amber' | 'gray' | 'red'
  icon: string // emoji or icon name hint for UI
}

// ─── Domain Classification ────────────────────────────────────────────────────

const CENTRAL_GOV_DOMAINS = [
  'gov.in', 'nic.in', 'india.gov.in', 'mygov.in', 'pgportal.gov.in',
]
const STATE_GOV_PATTERNS = [/\.[a-z]{2}\.gov\.in$/, /\.gov\.[a-z]{2}\.in$/]
const INSTITUTIONAL_DOMAINS = [
  'uidai.gov.in', 'epfo.gov.in', 'utiitsl.com', 'protean-tinpan.com',
  'passportindia.gov.in', 'parivahan.gov.in', 'incometax.gov.in',
  'nsp.gov.in', 'myaadhaar.uidai.gov.in',
]

/**
 * Classifies a URL into a source tier based on its domain.
 */
export function classifySourceTier(url: string): SourceTier {
  try {
    const parsed = new URL(url)
    const hostname = parsed.hostname.toLowerCase()

    if (INSTITUTIONAL_DOMAINS.some((d) => hostname === d || hostname.endsWith(`.${d}`))) {
      return 'VERIFIED_INSTITUTIONAL'
    }

    if (CENTRAL_GOV_DOMAINS.some((d) => hostname === d || hostname.endsWith(`.${d}`))) {
      return 'VERIFIED_OFFICIAL'
    }

    if (STATE_GOV_PATTERNS.some((p) => p.test(hostname))) {
      return 'VERIFIED_OFFICIAL'
    }

    return 'REQUIRES_CONFIRMATION'
  } catch {
    return 'REQUIRES_CONFIRMATION'
  }
}

// ─── Freshness Calculation ────────────────────────────────────────────────────

const FRESH_THRESHOLD_DAYS = 30
const RECENTLY_VERIFIED_THRESHOLD_DAYS = 90

/**
 * Calculates the freshness status of a source based on last verification date.
 */
export function calculateFreshness(lastVerifiedAt: string | null): FreshnessStatus {
  if (!lastVerifiedAt) return 'unknown'

  const verifiedDate = new Date(lastVerifiedAt)
  if (isNaN(verifiedDate.getTime())) return 'unknown'

  const daysSince = (Date.now() - verifiedDate.getTime()) / (1000 * 60 * 60 * 24)

  if (daysSince <= FRESH_THRESHOLD_DAYS) return 'fresh'
  if (daysSince <= RECENTLY_VERIFIED_THRESHOLD_DAYS) return 'recently_verified'
  return 'review_due'
}

// ─── Badge Generation ──────────────────────────────────────────────────────────

const TIER_BADGES: Record<SourceTier, AttributionBadge> = {
  VERIFIED_OFFICIAL: {
    label: 'Official Source',
    description: 'Information sourced from an official Government of India or state government portal.',
    tier: 'VERIFIED_OFFICIAL',
    color: 'green',
    icon: '✅',
  },
  VERIFIED_INSTITUTIONAL: {
    label: 'Verified Source',
    description: 'Sourced from a verified statutory or institutional body (e.g., UIDAI, EPFO, NSDL).',
    tier: 'VERIFIED_INSTITUTIONAL',
    color: 'blue',
    icon: '🔵',
  },
  SYSTEM_GUIDANCE: {
    label: 'AI Guidance',
    description: 'General guidance generated by TheervuAI. Verify with the official source before acting.',
    tier: 'SYSTEM_GUIDANCE',
    color: 'gray',
    icon: '🤖',
  },
  USER_PROVIDED: {
    label: 'User-Provided',
    description: 'Information entered by you. Not verified by TheervuAI.',
    tier: 'USER_PROVIDED',
    color: 'gray',
    icon: '👤',
  },
  REQUIRES_CONFIRMATION: {
    label: 'Verify Required',
    description: 'This information may be location-dependent or outdated. Verify with the official source.',
    tier: 'REQUIRES_CONFIRMATION',
    color: 'amber',
    icon: '⚠️',
  },
}

/**
 * Returns a UI-ready attribution badge for a source tier.
 */
export function getAttributionBadge(tier: SourceTier): AttributionBadge {
  return TIER_BADGES[tier]
}

/**
 * Formats a source record into a human-readable attribution string.
 * Safe for rendering in UI or including in AI responses.
 */
export function formatSourceAttribution(source: SourceRecord): string {
  const badge = TIER_BADGES[source.tier]
  const freshLabel = {
    fresh: '✓ Verified recently',
    recently_verified: '✓ Verified within 90 days',
    review_due: '⚠ May require re-verification',
    unknown: 'Verification date unknown',
  }[source.freshnessStatus]

  return `${badge.icon} ${badge.label}: ${source.title} — ${source.department} (${source.authority}) — ${freshLabel}`
}

/**
 * Builds a SourceRecord from a CivicService for AI response attribution.
 */
export function buildSourceRecord(params: {
  title: string
  url: string
  department: string
  authority: string
  state?: string
  lastVerifiedAt?: string
  notes?: string
}): SourceRecord {
  const tier = classifySourceTier(params.url)
  const freshnessStatus = calculateFreshness(params.lastVerifiedAt || null)

  return {
    title: params.title,
    url: params.url,
    department: params.department,
    authority: params.authority,
    state: params.state || 'All India',
    tier,
    lastVerifiedAt: params.lastVerifiedAt || null,
    freshnessStatus,
    notes: params.notes,
  }
}
